webtalk_init -webtalk_dir C:\\Users\\Usman\\Desktop\\ECE532\\Demo_Archive.xpr\\BlueMileStone_2\\BlueMileStone_2.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 29 19:58:20 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4ugo1ukgr7uhid4m2la6jif6a9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_29" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "29" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1490791809674" -context "sdk\\\\hardware/1490791809674"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1490791809674"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1490791809674"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.2" -context "sdk\\\\hardware/1490791809674"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1490791809674"
webtalk_add_data -client sdk -key Device -value "7a100t" -context "sdk\\\\hardware/1490791809674"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1490791809674"
webtalk_add_data -client sdk -key uid -value "1490791866042" -context "sdk\\\\bsp/1490791866042"
webtalk_add_data -client sdk -key hwid -value "1490791809674" -context "sdk\\\\bsp/1490791866042"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1490791866042"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1490791866042"
webtalk_add_data -client sdk -key uid -value "1490791872640" -context "sdk\\\\application/1490791872640"
webtalk_add_data -client sdk -key hwid -value "1490791809674" -context "sdk\\\\application/1490791872640"
webtalk_add_data -client sdk -key bspid -value "1490791866042" -context "sdk\\\\application/1490791872640"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1490791872640"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1490791872640"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1490791872640"
webtalk_transmit -clientid 2405869255 -regid "" -xml C:\\Users\\Usman\\Desktop\\ECE532\\Demo_Archive.xpr\\BlueMileStone_2\\BlueMileStone_2.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Usman\\Desktop\\ECE532\\Demo_Archive.xpr\\BlueMileStone_2\\BlueMileStone_2.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Usman\\Desktop\\ECE532\\Demo_Archive.xpr\\BlueMileStone_2\\BlueMileStone_2.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
